// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnQJWcdL3dxhE_QPUQO3rGrT0BBQF8y2Q',
    appId: '1:308832764565:web:046864e50ebfe150c8d19c',
    messagingSenderId: '308832764565',
    projectId: 'notificationapp-854d0',
    authDomain: 'notificationapp-854d0.firebaseapp.com',
    storageBucket: 'notificationapp-854d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnuldo6zLo78hFELV9klN5kCH2i9OVt0',
    appId: '1:308832764565:android:55c9fd91b953fbb8c8d19c',
    messagingSenderId: '308832764565',
    projectId: 'notificationapp-854d0',
    storageBucket: 'notificationapp-854d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKlErcuRNKcJ_rW1swAge56zifjSsliE',
    appId: '1:308832764565:ios:562b147099b50b8dc8d19c',
    messagingSenderId: '308832764565',
    projectId: 'notificationapp-854d0',
    storageBucket: 'notificationapp-854d0.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWKlErcuRNKcJ_rW1swAge56zifjSsliE',
    appId: '1:308832764565:ios:562b147099b50b8dc8d19c',
    messagingSenderId: '308832764565',
    projectId: 'notificationapp-854d0',
    storageBucket: 'notificationapp-854d0.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnQJWcdL3dxhE_QPUQO3rGrT0BBQF8y2Q',
    appId: '1:308832764565:web:5873120187cc861ac8d19c',
    messagingSenderId: '308832764565',
    projectId: 'notificationapp-854d0',
    authDomain: 'notificationapp-854d0.firebaseapp.com',
    storageBucket: 'notificationapp-854d0.firebasestorage.app',
  );
}
